print("Yo, johnnybob.")
print("Listen... I need 4 bucks. Just 4. Come on.")
print()
input("You: ")
print()
print("Bro... that's not what I asked. I just need 4 dollars man.")
print("You got venmo? cashapp? anything??")
print()
input("You: ")
print()
print("Forget it johnnybob. I'll remember this.")
